base_url = "https://example.com"
title = "Serene Theme"
description = "The demo site of zola blog theme serene"
default_language = "en"
theme = "serene"
output_dir = "docs"
compile_sass = true
minify_html = true
build_search_index = false
generate_feed = false
feed_filename = "feed.xml"
taxonomies = [
    {name = "tags"},
    {name = "categories"}
]

[markdown]
highlight_code = true
extra_syntaxes = []
highlight_theme = "nord"
render_emoji = true

[search]
include_title = true
include_description = false
include_path = false
include_content = true

[extra]
name = "Serene Theme"
id = "serene"
bio = "The demo site of zola blog theme serene"
avatar = "img/avatar.png"

show_id = true
show_projects = true

blog_icon = "ri-quill-pen-line"
projects_icon = "ri-compasses-2-line"
home_icon = "ri-user-6-line"
rss_icon = "ri-rss-line"
toc_icon = "ri-menu-2-line"

links = [
    {name = "GitHub", icon = "ri-github-line", url = "https://github.com/<your-username>"},
    {name = "Twitter", icon = "ri-twitter-line", url = "https://twitter.com/<your-username>"},
    {name = "Email", icon = "ri-mail-line", url = "mailto:<your-email-address>"}
]

toc = true
blur_effect = true
back_to_top_button = true
progress_bar = true
cc_license = true
cc_license_info = "This work is licensed under [CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/)."

outdate_warn = true
outdate_warn_days = 120
outdate_warn_text1 = "Note: This article was last updated "
outdate_warn_text2 = " days ago and may be out of date."

footer_copyright_name = "<your-name>"
footer_copyright_year = "2021"
# footer_custom = "xxxxxxxxxxxxxxxx"
footer_credits = true

feed_in_blog_section = true

comment = "none"
analytics = "none"



#======================= Comment =======================

[extra.gitalk]
client_id = "xxxxxxxx"
client_secret = "xxxxxxxx"
repo = "xxxxxxxx"
owner = "xxxx"
admin = ["xxxx"]
distraction_free_mode = false
per_page = 10
page_direction = "first"
proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token"

[extra.disqus]
shortname = "xxxx"

[extra.disqus_js]
shortname = "xxxx"
apikey = "xxxx"
# site_name = "xxxx"
# identifier = "xxxx"
# url = "xxxx"
# title = "xxxx"
# api = "xxxx"
# nesting = 4
# nocomment = "xxxx"
# admin = "xxxx"
# admin_label = "xxxx"


#======================= Analytics =======================

[extra.google_analytics]
id = "G-XXXXXXXX"  # or UA-XXXXXXXX

[extra.cloudflare_web_analytics]
token = "xxxxxxxx"

[extra.umami]
website_id = "xxxxx-xxxx-xxxxx"
src = "https://xxxxxxxxxxx/umami.js"

[extra.baidu_tongji]
token = "xxxxxxxx"