[[project]]
name = "Lorem"
desc = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et! Atque libero expedita laudantium cupiditate, sit explicabo sequi ipsa!"
links = [
    {name = "GitHub", url = "https://example.com"},
    {name = "Docs", url = "https://example.com"},
]

[[project]]
name = "Lorem ipsum"
desc = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et! Atque libero expedita laudantium cupiditate, sit explicabo sequi ipsa!"
links = [
    {name = "HomePage", url = "https://example.com"},
    {name = "GitHub", url = "https://example.com"},
    {name = "Docs", url = "https://example.com"},
]

[[project]]
name = "Dolor Sit"
desc = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et! Atque libero expedita laudantium cupiditate, sit explicabo sequi ipsa!"
links = [
    {name = "GitHub", url = "https://example.com"},
]

[[project]]
name = "amet"
desc = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et! Atque libero expedita laudantium cupiditate, sit explicabo sequi ipsa!"
links = [
    {name = "HomePage", url = "https://example.com"},
    {name = "GitHub", url = "https://example.com"},
    {name = "Docs", url = "https://example.com"},
    {name = "Wiki", url = "https://example.com"},
]

[[project]]
name = "lorem-ipsum"
desc = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et! Atque libero expedita laudantium cupiditate, sit explicabo sequi ipsa!"
links = [
    {name = "GitHub", url = "https://example.com"},
    {name = "Docs", url = "https://example.com"},
]

[[project]]
name = "Praesentium"
desc = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et! Atque libero expedita laudantium cupiditate, sit explicabo sequi ipsa!"
links = [
    {name = "HomePage", url = "https://example.com"},
    {name = "GitHub", url = "https://example.com"},
    {name = "Docs", url = "https://example.com"},
]