[[project]]
name = "zola-theme-serene"
desc = "Serene is a simple yet feature-rich blog theme for Static-Site-Generator Zola."
links = [
    {name = "GitHub", url = "https://gitub.com/isunjn/serene"},
    {name = "Docs", url = "https://github.com/isunjn/serene/wiki"},
]